### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sooroos** [pedroborges/kirby-page-lock#12]
it does not work at all

edit:155 
POST http://localhost/page-lock/lock?page=/kirby2/panel/pages/projects 404 (Not Found)
ajax @ edit:155
lock @ edit:257
init @ edit:193
Lock @ edit:180
$.fn.lock @ js?v=2.5.10:17
(anonymous) @ panel.min.js?v=2.5.10:7
each @ panel.min.js?v=2.5.10:3
each @ panel.min.js?v=2.5.10:2
Form @ panel.min.js?v=2.5.10:7
o @ panel.min.js?v=2.5.10:7
h @ panel.min.js?v=2.5.10:7
setup @ app.min.js?v=2.5.10:1
(anonymous) @ app.min.js?v=2.5.10:1
u @ panel.min.js?v=2.5.10:3
fireWith @ panel.min.js?v=2.5.10:3
ready @ panel.min.js?v=2.5.10:3
s @ panel.min.js?v=2.5.10:2

**Comment by pedroborges** [comment]
Solved by 43da2d5
