### ISSUE TITLE
Kirby Panel error message when using the field

### ISSUE THREAD

**Issue by bugsysop** [pedroborges/kirby-page-lock#3]
When I add te `pagelock` field to a `blueprint`, and then try to edit a page using this `blueprint`, I have this error message:

```
Fatal error: Using $this when not in object context in /Applications/MAMP/htdocs/test/panel/app/helpers.php on line 32
```

I am on a local web server (using MAMP on Mac), and use Kirby 2.3

The `pagelock`directory is correctly installed in the `site/fields` directory, and at the end of my `blueprint` I inserted as said in `readme`file:

```
      pagelock:
        type: pagelock
```

**Comment by pedroborges** [comment]
I just tried on Kirby 2.3.1 and didn't get this error, turns out it's a Kirby bug introduced in 2.3.0. Gladly it's been fixed in 2.3.1, see: getkirby/panel@566e29f3

So upgrading to 2.3.1 solves your issue.

Thanks for trying out pagelock, I'd love to hear your feedback.

**Comment by bugsysop** [comment]
Will try soon the 2.3.1. Thank !!!

**Comment by pedroborges** [comment]
If for some reason you can't upgrade right now, you can still change `panel/app/helpers.php` line 32 to be `$translation = a::get($value, kirby()->option('panel.language'));` to get rid of the error.

**Comment by bugsysop** [comment]
Nice. Tried with Kirby 2.3.1 it solved the probem.
