### ISSUE TITLE
Suggestion to use this as standalone pagelock

### ISSUE THREAD

**Issue by Thiousi** [pedroborges/kirby-page-lock#4]
Here's an idea I hope you'll like! Your pagelock is great and I think of a use case where it'd be perfect:

Always locking the page until we get user roles. This way we can prevent certain users from editing the page. Is that understandable?

This could be a field option?

```
pagelock:
  type: pagelock
  force: true
```

And maybe, but this is me just throwing ideas out here, maybe you could instead of just "true" use a list of user roles?

This may be better off as a separate field.

**Comment by pedroborges** [comment]
With Kirby's new permission feature this is no longer relevant.
